# Generated by Django 2.2 on 2019-10-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantegra_staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
