# Generated by Django 2.2 on 2019-10-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantegra_staff', '0002_delete_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Profile Image'),
        ),
    ]
