# Generated by Django 2.2 on 2019-10-04 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('plantegra_crm', '0002_auto_20191003_1940'), ('plantegra_crm', '0003_taskforce_working_day'), ('plantegra_crm', '0004_auto_20191003_2246'), ('plantegra_crm', '0005_remove_taskforce_members'), ('plantegra_crm', '0006_taskforce_members'), ('plantegra_crm', '0007_auto_20191004_0958')]

    dependencies = [
        ('plantegra_resources', '0001_initial'),
        ('plantegra_staff', '0002_delete_team'),
        ('plantegra_crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_line1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_line2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address Line 2'),
        ),
        migrations.CreateModel(
            name='TaskForce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantegra_resources.Vehicle', verbose_name='Vehicle')),
                ('working_day', models.DateField(default=datetime.date.today, verbose_name='Date of deployment')),
                ('members', models.ManyToManyField(to='plantegra_staff.Employee', verbose_name='Members')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='task_force',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='plantegra_crm.TaskForce'),
        ),
    ]
