# Generated by Django 2.2 on 2019-10-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantegra_crm', '0002_create_taskforce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plantegra_crm.Address'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='task_force',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='plantegra_crm.TaskForce'),
        ),
        migrations.AlterField(
            model_name='taskforce',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantegra_resources.Vehicle', verbose_name='Vehicle'),
        ),
    ]
