# Generated by Django 2.2 on 2019-04-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantegra_crm', '0002_remove_appointment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
