# Generated by Django 2.2 on 2019-05-05 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plantegra_resources.Resource')),
                ('model', models.CharField(max_length=200, verbose_name='Vehicle Model')),
                ('plate_number', models.CharField(max_length=20, verbose_name='Plate number')),
            ],
            bases=('plantegra_resources.resource',),
        ),
    ]
